site_name: stack-overflowers
site_description: "Main documentation for stack-overflowers project"
repo_url: https://github.com/xgeeks-geekathon/stack-overflowers.git
edit_uri: edit/master/docs

# plugins:
#   - techdocs-core

# For sidebar navigation
nav:
  - Getting Started: "index.md"
